#!/usr/bin/env node
/**
 * Emit every numeric claim on the /funding pages, in reading order.
 *
 * Companion to docs/advance-rate-verification.md. That doc is risk-ranked, for
 * someone with fifteen minutes. This one is page-ordered, for someone walking
 * the pages properly — which is how Michael said he wanted to review them.
 *
 *   npx tsx scripts/extract-rate-claims.ts > docs/rate-claims-by-page.md
 *
 * Re-run after any copy change so the review list never drifts from the pages.
 */

import { fundingPages } from '../src/data/funding-pages'

/** Over-inclusive on purpose: a missed claim costs more than a skimmed line. */
const hasNumber = (t: string) => /\d/.test(t)

const sentences = (text: string) =>
  text
    .split(/\n\n+/)
    .flatMap(para => para.split(/(?<=[.:])\s+(?=[A-Z(])/))
    .map(s => s.trim())
    .filter(s => s && hasNumber(s))

const out: string[] = [
  '# Every numeric claim on the /funding pages, in reading order',
  '',
  'Generated by `scripts/extract-rate-claims.ts`. Re-run after any copy change.',
  '',
  'This is the walk-the-pages version. For the fifteen-minute, risk-ranked version',
  'see [advance-rate-verification.md](advance-rate-verification.md).',
  '',
  'For each claim: confirm it, correct it, or say "varies too much to publish" and',
  'it gets widened or cut.',
  '',
]

for (const p of fundingPages) {
  out.push(`## ${p.h1}`, '', `\`/funding/${p.id}\``, '')

  const section = (title: string, items: string[]) => {
    if (!items.length) return
    out.push(`**${title}**`, '')
    for (const i of items) out.push(`- ${i}`)
    out.push('')
  }

  section('Opening answer', sentences(p.directAnswer))
  section('Where this fits best', p.fitsIf.filter(hasNumber))
  section('How it works', p.howItWorks.filter(s => hasNumber(s.detail)).map(s => `*${s.step}* — ${s.detail}`))
  section('Terms table', p.terms.filter(t => hasNumber(t.value)).map(t => `**${t.label}:** ${t.value}`))
  section(
    p.versus.heading,
    p.versus.rows
      .filter(r => hasNumber(r.theirs) || hasNumber(r.ours))
      .map(r => `**${r.dimension}** — them: ${r.theirs} · us: ${r.ours}`)
  )
  section('Worked example', sentences(p.workedExample))
  section('When this is the wrong answer', p.notFor.filter(n => hasNumber(n.who) || hasNumber(n.instead)).map(n => `*${n.who}* — ${n.instead}`))
  section('FAQ', p.faqs.filter(f => hasNumber(f.answer)).map(f => `*${f.question}* — ${f.answer}`))
}

const claims = out.filter(l => l.startsWith('- ')).length
out.push('---', '', `${claims} numeric claims across ${fundingPages.length} pages.`)

console.log(out.join('\n'))
